from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class RAGQueryRequest(BaseModel):
    """Schema for a teacher asking a question about student learning data."""
    query: str = Field(
        ...,
        description="Natural language question regarding student learning data",
        min_length=1,
    )
    class_id: Optional[str] = Field(None, description="Optional class ID filter")
    student_ids: Optional[List[str]] = Field(
        None, description="Optional list of specific student IDs to filter by"
    )
    top_k: int = Field(5, ge=1, le=20, description="Number of context documents to retrieve")


class CitationSource(BaseModel):
    """Schema representing a citation source used by RAG system."""
    source_id: str
    title: str
    content_snippet: str
    relevance_score: Optional[float] = Field(None, ge=0.0, le=1.0)


class RAGQueryResponse(BaseModel):
    """Schema returning summarized information from the RAG system."""
    query: str
    answer: str = Field(..., description="Summarized answer generated by RAG system")
    sources: List[CitationSource] = Field(
        default_factory=list, description="List of source citations used"
    )
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0)


class TopicPerformance(BaseModel):
    """Schema for topic-wise student performance breakdown."""
    topic: str
    average_score: float = Field(..., ge=0.0, le=100.0)
    mastery_level: str = Field(
        ..., description="Mastery classification (e.g. Needs Improvement, Proficient, Advanced)"
    )


class MisconceptionDetail(BaseModel):
    """Schema for frequently occurring student misconceptions."""
    misconception_id: str
    description: str
    topic: str
    frequency_count: int = Field(..., ge=0)
    affected_students_count: int = Field(..., ge=0)


class StudentPerformanceOverview(BaseModel):
    """Schema for individual student performance summary in comparison context."""
    student_id: str
    student_name: str
    overall_score: float = Field(..., ge=0.0, le=100.0)
    topics_mastered: int = Field(..., ge=0)
    topics_struggling: int = Field(..., ge=0)


class StudentComparisonResponse(BaseModel):
    """Schema for comparing student performance, topic-wise metrics, and misconceptions."""
    class_id: str
    total_students: int = Field(..., ge=0)
    student_performances: List[StudentPerformanceOverview] = Field(default_factory=list)
    topic_performances: List[TopicPerformance] = Field(default_factory=list)
    frequent_misconceptions: List[MisconceptionDetail] = Field(default_factory=list)
